# Generated by Django 2.2.23 on 2021-05-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.Colaborador'),
        ),
    ]
