# Generated by Django 2.2.23 on 2021-05-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agenda_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='colaboradores.Colaborador'),
        ),
    ]
