# Generated by Django 2.2.23 on 2021-05-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0001_initial'),
        ('unidades', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.Paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='unidades.Unidade'),
        ),
    ]
